language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 8.0

before_script:
  - composer install --dev --optimize-autoloader
  - mkdir -p tests/reports

script:
  - bin/phpunit --verbose
  - npm install
  - npm run lint:style
  - npm run lint:js
  - npm run test:coverage
  - npm run build

after_script:
  - ls -lha
  - ls -lha coverage
  - ls -lha tests/reports
  - travis_retry php bin/php-coveralls -v -x tests/reports/clover.xml -x coverage/clover.xml -o tests/reports/coveralls.json
  - ./build.sh

cache:
  directories:
    - vendor
    - src/node_modules
