language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer update
  - composer install --dev --optimize-autoloader
  - mkdir -p tests/reports

script:
  - phpunit --verbose
  - cd src && npm install && npm run build && cd ..

after_script:
  - travis_retry php bin/php-coveralls -v -x tests/reports/clover.xml -o tests/reports/coveralls.json
  - ./build.sh

cache:
  directories:
    - vendor
    - src/node_modules
